# Generated by Django 5.2.7 on 2025-10-15 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["author"], "verbose_name_plural": "books"},
        ),
    ]
